sudo: required

language: php
php:
  - '7.0'

env:
  global:
  - NODE_ENV=test
  - PGPORT=5432
  - PGHOST=localhost

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

before_install:
  - psql --version

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "karmashard";'
  - composer install
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit -c app
