sudo: false

language: php
php:
  - '7.0'

env:
  global:
  - NODE_ENV=test
  - PGPORT=5432
  - PGHOST=localhost

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database "karmasharddb";'
  - composer install
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit --coverage-clover
