language: php
php:
  - '7.0'

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit -c app
