<?php

namespace AppBundle\Repository;

/**
 * ActionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
